version: '3'
services:

  elasticsearch:
    image: elasticsearch:5
    #command: -Des.node.name="hera_elasticsearch_001" -Des.bootstrap.mlockall=true
    command: -Des.bootstrap.mlockall=true
    environment:
     - ES_HEAP_SIZE=2g

  kibana:
    image: kibana:5
    depends_on:
     - elasticsearch
    ports:
     - 5601:5601

  logstash:
    #image: logstash:5
    build: ./build/logstash/.
    command: -f /config-dir/
    environment:
     - LS_HEAP_SIZE=2048m
    depends_on:
     - elasticsearch
    volumes:
     - ./run/logstash/config:/config-dir
     - ./run/mib:/mib
     - ./run/logstash/ssl:/etc/pki/tls
    ports:
     - "5000:5000/udp"
     - "5001:5001"
